name = "dream-expert-analysis"
main = "build/worker/shim.mjs"
workers_dev = true
compatibility_date = "2024-08-19"

[build]
command = "cargo install -q worker-build && PATH=$HOME/.cargo/bin:$PATH worker-build --release"

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[ai]
binding = "AI"
